environment: dev

spring:
  datasource:
    url: jdbc:mysql://os-chat.c3cgpbny0gbg.us-east-1.rds.amazonaws.com:3306/os
    username: admin
    password: oschat2022
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

